### PR TITLE
feat(runtime-config): experimental env expansion support

### PR DESCRIPTION
**Pull request by Vespand**
### 🔗 Linked issue

There no linked issue, because this is feature

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Feature add additional check env for used in runtime config templates like: `{{MAIL_HOST}}`
For example instead of (actual small part of runtime config app):

```js
export default defineNuxtConfig({
    runtimeConfig: {
        public: {
            auth: {
                strategies: {
                    some: {
                        endpoints: {
                            authorization: '', // NUXT_PUBLIC_AUTH_STRATEGIES_SOME_ENDPOINTS_AUTHORIZATION
                            userInfo: '', // NUXT_PUBLIC_AUTH_STRATEGIES_SOME_ENDPOINTS_USER_INFO
                            token: '', // NUXT_PUBLIC_AUTH_STRATEGIES_SOME_ENDPOINTS_TOKEN
                            logout: '' // NUXT_PUBLIC_AUTH_STRATEGIES_SOME_ENDPOINTS_LOGOUT
                        },
                        clientId: '' // NUXT_PUBLIC_AUTH_STRATEGIES_SOME_CLIENT_ID
                    }
                }
            }
        }
    }
});
```
We can use (with `envExpansion: true`):
```js
export default defineNuxtConfig({
    runtimeConfig: {
        public: {
            auth: {
                strategies: {
                    some: {
                        endpoints: {
                            authorization: '{{HOST_SCHEMA}}://{{AUTH_HOST}}/authorization',
                            userInfo: '{{HOST_SCHEMA}}://{{AUTH_HOST}}/userInfo',
                            token: '{{HOST_SCHEMA}}://{{AUTH_HOST}}/token',
                            logout: '{{HOST_SCHEMA}}://{{AUTH_HOST}}/logout'
                        },
                        clientId: '{{AUTH_CLIENT_ID}}'
                    }
                }
            }
        }
    }
});
```

This feature targeting developer experience with best practices from other frameworks and programming languages
By default it is off.

Now working with envs in Nuxt is pain, because:
- Envs can't be reused (need to set a lot of variables)
- Long env names (developer can get typo error when adding long-name env)
- Hardcode and no flexability with env name in Nuxt and env name in environment

Case of this is setting up environment env for dynamic environments (including production), where you have different backends, sso paths, clients and others integrations and can't reuse same env for others (like `HOST_SCHEMA`)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

Looking for feedback about this feature :)
If it's ok, will add docs
For now added example and tests with some cases

### CODE REVIEW

**Comment by pi0** [comment]
Thanks so much for this it is gonna be really useful! I expect at some point we enable this behavior by default. With latest changes, users can opt-in using `experimental.envExpansion` config (`nitro.experimental.envExpansion` for nuxt)

**Comment by manniL** [comment]
@pi0 I wonder, will the replacement also work during runtime? 🤔
Mainly referring to because of the 1:1 env replacements (see e.g. what [I've shown in my video](https://www.youtube.com/watch?v=_FYV5WfiWvs) / [this docs PR](https://github.com/nuxt/nuxt/pull/24612))

**Comment by pi0** [comment]
Yes it works!

**Comment by edimitchel** [comment]
Will this feature be out of experimental for next major version? This would be a better way for avoiding to be tight to named environment variable (NUXT_XXX_XXX) for runtime config variables.

**Comment by pi0** [comment]
(sadly) perhaps not and become an opt-in flag (instead of experimental) see [this pnpm article](https://pnpm.io/blog/2026/06/11/env-variables-in-repository-npmrc).

**Comment by edimitchel** [comment]
Hoo sad! Is there another way (under consideration) to handle runtime config instead of of named environment variables?

**Comment by septatrix** [comment]
> (sadly) perhaps not and become an opt-in flag (instead of experimental) see [this pnpm article](https://pnpm.io/blog/2026/06/11/env-variables-in-repository-npmrc).

Hm, if that attack vector is really a concern making it opt-in does not change a thing. If an attacker manipulates the Nuxt config to exfiltrate some env vars and publish them, they can simply enable the same flag in the config. Unless I understand the attack vector wrong?

**Pull request merged**
